//* authActions
export const SET_USER = "SET_USER";

//* contactsActions
export const GET_CONTACTS = "GET_CONTACTS";
export const GET_USERAPP = "GET_USERAPP";
export const RESET_CONTACTS_REDUCER = "RESET_CONTACTS_REDUCER";

//* chatActions
export const CHAT_USER = "CHAT_USER";
export const CONVERSATION_ID = "CONVERSATION_ID";
export const GET_CONVERSATIONS = "GET_CONVERSATIONS";
export const GET_MESSAGES = "GET_MESSAGES";
export const GET_OWN_CONVERSATIONS = "GET_OWN_CONVERSATIONS";
export const IS_AT_LEAST_ONE_CONVERSATION_SELECTED = "IS_AT_LEAST_ONE_CONVERSATION_SELECTED";
export const IS_AT_LEAST_ONE_MESSAGE_SELECTED = "IS_AT_LEAST_ONE_MESSAGE_SELECTED";
export const RESET_CHAT_MESSAGES = "RESET_CHAT_MESSAGES";
export const RESET_CHAT_REDUCER = "RESET_CHAT_REDUCER";
export const SCROLL_TO_LAST_MESSAGE = "SCROLL_TO_LAST_MESSAGE";
export const SELECT_MESSAGE = "SELECT_MESSAGE";
export const SELECT_CONVERSATION = "SELECT_CONVERSATION";

